---
name: Enhancement Request
description: Template to submit a enhancement request against ACI as Code
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this enhancement request!

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the enhancement is.
      placeholder: Tell us what you want to see!
    validations:
      required: true

  - type: checkboxes
    id: aci-version
    attributes:
      label: ACI/NDO Version
      description: Specify the ACI or NDO version related to the enhancement.
      options:
        - label: ACI 4.x
        - label: ACI 5.x
        - label: ACI 6.0.x
        - label: ACI 6.1.x
        - label: NDO 4.2
        - label: NDO 4.3
        - label: NDO 4.4
    validations:
      required: false

  - type: input
    id: customer-name
    attributes:
      label: Associated Customer
      description: Provide customer name if applicable.
      placeholder: Customer name
    validations:
      required: true

  - type: dropdown
    id: services-as-code
    attributes:
      label: Is this a customer of Services as Code (LCS)?
      description: Is the issue opened for a customer with paid Services as Code support?
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true

  - type: input
    id: customer-pid
    attributes:
      label: Project PID/DID
      description: Provide Project PID or deal ID to prioritize the issue.
      placeholder: Project Project PID or deal ID
    validations:
      required: false
